config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :crews
  get 'api_html/portal'
  get 'dashboard', to: 'api_html#dashboard'
  get 'api_html/techschedule'
  get 'api_html/makecall'
  resources :notes do
    collection do
      match 'api', to: 'notes#api', via: [:get, :post], defaults: { format: :json }
    end
  end






  namespace :api, defaults: { format: :json } do
    resources :sessions, only: [:create]
    resources :service_manager, only: [:create, :destroy] # Modify this line as needed
    post 'service_manager/auto_schedule', to: 'service_manager#auto_schedule'  # adding api at the begining seems to break
    post 'service_manager/make_appointment', to: 'service_manager#make_appointment'
    get 'service_manager/view_open', to: 'service_manager#view_open'
    get 'service_manager/view_sync', to: 'service_manager#view_sync'
    get 'service_manager/view_all', to: 'service_manager#view_all'
    get 'service_manager/view_by_tech', to: 'service_manager#view_by_tech'
    get 'service_manager/modal', to: 'service_manager#modal'
    get 'service_manager/get_day', to: 'service_manager#get_day'
    post 'service_manager/inner_notes', to: 'service_manager#inner_notes'
    put 'service_manager/sync_complete', to: 'service_manager#sync_complete'
    put 'service_manager/sync_kick_back', to: 'service_manager#sync_kick_back'
    put 'service_manager/sync_kick_back', to: 'service_manager#sync_kick_back'
    get 'service_manager/close_call', to: 'service_manager#close_call'
    get 'service_manager/rescheduleCallAvailableSlots', to: 'service_manager#rescheduleCallAvailableSlots'
    get 'service_manager/view_not_scheduled', to: 'service_manager#view_not_scheduled'

  end
  get 'Appointment_Portal', to: 'api_html#portal'






  get 'schedules/available_slots', to: 'schedules#available_slots'
  get 'schedules/days_by_proximity', to: 'schedules#days_by_proximity'

  resources :days do
    collection do
      match 'api', to: 'days#api', via: [:get, :post, :put, :patch, :delete], defaults: { format: :json }
    end
  end
  resources :samsungcalls do
    collection do
      match 'api', to: 'samsungcalls#api', via: [:get, :post, :put, :patch, :delete], defaults: { format: :json }
    end
  end
 

  resources :twilio_actions, only: [:index, :create] do
    collection do
      post 'make_call'
      post 'send_text'
      post 'disconnect_call'
    end
  end

  post 'start_conference_call', to: 'twilio_actions#start_conference_call'
  post 'initiate_call_and_join_conference', to: 'twilio_actions#initiate_call_and_join_conference'
  post 'join_conference', to: 'twilio_actions#join_conference'
  post 'disconnect_call', to: 'twilio_actions#disconnect_call'
  post 'dial', to: 'twilio_actions#dial'
  get 'schedules', to: 'schedules#index'
  resources :agents
  resources :technicians
  resources :payments do 
    resources :receipts
  end
  resources :orders do
    resources :payments
  end
  resources :customers do 
    resources :orders
  end
  resources :web_calls
  get 'twilio/voice'
  resources :calls
  resources :reps
  

  get 'helpful', to: 'pages#helpLink', as: :helpLink
  get 'pportal', to: 'pages#phonePortal', as: :phonePortal
  get 'Appliance Hospital', to: 'pages#hospital', as: :hospital
  get 'Extended Warranties', to: 'pages#warranties', as: :warranties
  get 'Appliance Parts', to: 'pages#parts', as: :parts
  get 'Appliance Repair Near Me', to: 'pages#nearme', as: :nearme
  get 'Helpful Articles', to: 'pages#article', as: :article
  get 'Best Appliance', to: 'pages#best', as: :best
  get 'Repair Cost', to: 'pages#cost', as: :cost
  get 'pages/aux'
  root 'pages#frontdoor'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/samsungcall.rb
class Samsungcall < ApplicationRecord
	before_validation :set_default_phone, on: :create
	belongs_to :day, optional: true


	def set_default_phone
	    self.phone1 ||= 'none'
	    self.phone2 ||= 'none'
	end
end

app/controllers/samsungcalls_controller.rb
class SamsungcallsController < ApplicationController
  include TwilioActionsHelper
  skip_before_action :verify_authenticity_token, only: [:api]
  before_action :authenticate_token, only: [:api]
  before_action :set_samsungcall, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_crew!, except: [:api] #devise helper
  before_action :set_user_id, except: [:api]


  API_BASE_URL = ENV["API_BASE_URL"]


  # GET /samsungcalls
  # GET /samsungcalls.json
  def index
    
    @samsungcalls = Samsungcall.all
  end

  # GET /samsungcalls/1
  # GET /samsungcalls/1.json
  def show
  end

  # GET /samsungcalls/new
  def new
    @samsungcall = Samsungcall.new
  end

  # GET /samsungcalls/1/edit
  def edit
  end

  # POST /samsungcalls
  # POST /samsungcalls.json
  def create
    @samsungcall = Samsungcall.new(samsungcall_params)

    respond_to do |format|
      if @samsungcall.save
        format.html { redirect_to @samsungcall, notice: 'Samsungcall was successfully created.' }
        format.json { render :show, status: :created, location: @samsungcall }
      else
        format.html { render :new }
        format.json { render json: @samsungcall.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /samsungcalls/1
  # PATCH/PUT /samsungcalls/1.json
  def update
    respond_to do |format|
      if @samsungcall.update(samsungcall_params)
        format.html { redirect_to @samsungcall, notice: 'Samsungcall was successfully updated.' }
        format.json { render :show, status: :ok, location: @samsungcall }
      else
        format.html { render :edit }
        format.json { render json: @samsungcall.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /samsungcalls/1
  # DELETE /samsungcalls/1.json
  def destroy
    @samsungcall.destroy
    respond_to do |format|
      format.html { redirect_to samsungcalls_url, notice: 'Samsungcall was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # API controller action for CRUD actions
  def api
    respond_to do |format|
      format.json {
        case request.method_symbol
        when :get
        if params[:id]
          @samsungcall = Samsungcall.find(params[:id])
          render json: @samsungcall
        else
          @samsungcalls = Samsungcall.all
          render json: @samsungcalls
        end
        when :post
          @samsungcall = Samsungcall.new(samsungcall_params)
          if @samsungcall.save
            render json: @samsungcall, status: :created
          else
            render json: @samsungcall.errors, status: :unprocessable_entity
          end
        when :put, :patch
          @samsungcall = Samsungcall.find(params[:id])
          if @samsungcall.update(samsungcall_params)
            render json: @samsungcall, status: :ok
          else
            render json: @samsungcall.errors, status: :unprocessable_entity
          end
        when :delete
          @samsungcall = Samsungcall.find(params[:id])
          @samsungcall.destroy
          head :no_content
        end
      }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_samsungcall
      @samsungcall = Samsungcall.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def samsungcall_params
      params.require(:samsungcall).permit(:fourk, :name, :phone1, :phone2, :email, :address, :zipcode, :hass, :status, :note, :flag, :day_id)
    end
end

app/helpers/samsungcalls_helper.rb
module SamsungcallsHelper
end

app/views/samsungcalls/_form.html.erb
<%= form_with(model: samsungcall, local: true) do |form| %>
  <% if samsungcall.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(samsungcall.errors.count, "error") %> prohibited this samsungcall from being saved:</h2>

      <ul>
        <% samsungcall.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :fourk %>
    <%= form.text_field :fourk %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="form-content">
    <label for="samsungcall_phone1">Phone1</label>
    <%= text_field_tag 'samsungcall[phone1]', @samsungcall.phone1 || "none", id: 'samsungcall_phone1' %>
  </div>

  <div class="form-content">
    <label for="samsungcall_phone2">Phone2</label>
    <%= text_field_tag 'samsungcall[phone2]', @samsungcall.phone2 || "none", id: 'samsungcall_phone2' %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :zipcode %>
    <%= form.text_field :zipcode %>
  </div>


  <div class="field">
    <%= form.label :hass %>
    <%= form.check_box :hass %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.number_field :status %>
  </div>
   <div class="field">
    <%= form.label :day_id %>
    <%= form.text_field :day_id %>
  </div>

  <div class="field">
    <%= form.label :note %>
    <%= form.text_field :note %>
  </div>

  <div class="field">
    <%= form.label :flag %>
    <%= form.number_field :flag %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/samsungcalls/edit.html.erb
<h1>Editing Samsungcall</h1>

<%= render 'form', samsungcall: @samsungcall %>

<%= link_to 'Show', @samsungcall %> |
<%= link_to 'Back', samsungcalls_path %>

app/views/samsungcalls/index.html.erb
<p id="notice"><%= notice %></p>
<% content_for :javascript_packs do %>
  <%= javascript_pack_tag 'samsungcalls.js' %>
<% end %>
<h1>Samsungcalls</h1>

<table>
  <thead>
    <tr>
      <th>Fourk</th>
      <th>Name</th>
      <th>Phone1</th>
      <th>Phone2</th>
      <th>Email</th>
      <th>Address</th>
      <th>Zipcode</th>
      <th>Day</th>
      <th>Hass</th>
      <th>Status</th>
      <th>Note</th>
      <th>Flag</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @samsungcalls.each do |samsungcall| %>
      <tr>
        <td><%= samsungcall.fourk %></td>
        <td id=<%=  samsungcall.id %>><%= samsungcall.name %></td>
        <td><%= samsungcall.phone1 %></td>
        <td><%= samsungcall.phone2 %></td>
        <td><%= samsungcall.email %></td>
        <td><%= samsungcall.address %></td>
        <td><%= samsungcall.zipcode %></td>
        <td>
          <% if samsungcall.day.nil? %>
            No appointment
          <% else %>
            <%= samsungcall.day.date %>
          <% end %>
        </td>
        <td><%= samsungcall.hass %></td>
        <td class='status'><%= samsungcall.status %></td>
        <td><%= samsungcall.note %></td>
        <td><%= samsungcall.flag %></td>
        <td><%= link_to 'Show', samsungcall %></td>
        <td><%= link_to 'Edit', edit_samsungcall_path(samsungcall) %></td>
        <td><%= link_to 'Destroy', samsungcall, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><button class="auto-schedule" data-value="<%= samsungcall.id %>"type="button">Send Auto App</button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Samsungcall', new_samsungcall_path %>
<h2><i id="note-icon" class="bi bi-journal-plus"></i></h2>
<%= link_to "Logout", destroy_crew_session_path, method: :delete %>

app/views/samsungcalls/new.html.erb
<h1>New Samsungcall</h1>

<%= render 'form', samsungcall: @samsungcall %>

<%= link_to 'Back', samsungcalls_path %>

app/views/samsungcalls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fourk:</strong>
  <%= @samsungcall.fourk %>
</p>

<p>
  <strong>Name:</strong>
  <%= @samsungcall.name %>
</p>

<p>
  <strong>Phone1:</strong>
  <%= @samsungcall.phone1 %>
</p>

<p>
  <strong>Phone2:</strong>
  <%= @samsungcall.phone2 %>
</p>

<p>
  <strong>Email:</strong>
  <%= @samsungcall.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @samsungcall.address %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @samsungcall.zipcode %>
</p>
<p>
  <strong>Day:</strong>
  <% if @samsungcall.day.nil? %>
     No appointment
  <% else %>
    <%= @samsungcall.day.date %>
  <% end %>
</p>

<p>
  <strong>Hass:</strong>
  <%= @samsungcall.hass %>
</p>

<p>
  <strong>Status:</strong>
  <%= @samsungcall.status %>
</p>

<p>
  <strong>Note:</strong>
  <%= @samsungcall.note %>
</p>

<p>
  <strong>Flag:</strong>
  <%= @samsungcall.flag %>
</p>

<%= link_to 'Edit', edit_samsungcall_path(@samsungcall) %> |
<%= link_to 'Back', samsungcalls_path %>