config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :crews
  get 'api_html/portal'
  get 'dashboard', to: 'api_html#dashboard'
  get 'api_html/techschedule'
  get 'api_html/makecall'
  resources :notes do
    collection do
      match 'api', to: 'notes#api', via: [:get, :post], defaults: { format: :json }
    end
  end






  namespace :api, defaults: { format: :json } do
    resources :sessions, only: [:create]
    resources :service_manager, only: [:create, :destroy] # Modify this line as needed
    post 'service_manager/auto_schedule', to: 'service_manager#auto_schedule'  # adding api at the begining seems to break
    post 'service_manager/make_appointment', to: 'service_manager#make_appointment'
    get 'service_manager/view_open', to: 'service_manager#view_open'
    get 'service_manager/view_sync', to: 'service_manager#view_sync'
    get 'service_manager/view_all', to: 'service_manager#view_all'
    get 'service_manager/view_by_tech', to: 'service_manager#view_by_tech'
    get 'service_manager/modal', to: 'service_manager#modal'
    get 'service_manager/get_day', to: 'service_manager#get_day'
    post 'service_manager/inner_notes', to: 'service_manager#inner_notes'
    put 'service_manager/sync_complete', to: 'service_manager#sync_complete'
    put 'service_manager/sync_kick_back', to: 'service_manager#sync_kick_back'
    put 'service_manager/sync_kick_back', to: 'service_manager#sync_kick_back'
    get 'service_manager/close_call', to: 'service_manager#close_call'
    get 'service_manager/rescheduleCallAvailableSlots', to: 'service_manager#rescheduleCallAvailableSlots'
    get 'service_manager/view_not_scheduled', to: 'service_manager#view_not_scheduled'

  end
  get 'Appointment_Portal', to: 'api_html#portal'






  get 'schedules/available_slots', to: 'schedules#available_slots'
  get 'schedules/days_by_proximity', to: 'schedules#days_by_proximity'

  resources :days do
    collection do
      match 'api', to: 'days#api', via: [:get, :post, :put, :patch, :delete], defaults: { format: :json }
    end
  end
  resources :samsungcalls do
    collection do
      match 'api', to: 'samsungcalls#api', via: [:get, :post, :put, :patch, :delete], defaults: { format: :json }
    end
  end
 

  resources :twilio_actions, only: [:index, :create] do
    collection do
      post 'make_call'
      post 'send_text'
      post 'disconnect_call'
    end
  end

  post 'start_conference_call', to: 'twilio_actions#start_conference_call'
  post 'initiate_call_and_join_conference', to: 'twilio_actions#initiate_call_and_join_conference'
  post 'join_conference', to: 'twilio_actions#join_conference'
  post 'disconnect_call', to: 'twilio_actions#disconnect_call'
  post 'dial', to: 'twilio_actions#dial'
  get 'schedules', to: 'schedules#index'
  resources :agents
  resources :technicians
  resources :payments do 
    resources :receipts
  end
  resources :orders do
    resources :payments
  end
  resources :customers do 
    resources :orders
  end
  resources :web_calls
  get 'twilio/voice'
  resources :calls
  resources :reps
  

  get 'helpful', to: 'pages#helpLink', as: :helpLink
  get 'pportal', to: 'pages#phonePortal', as: :phonePortal
  get 'Appliance Hospital', to: 'pages#hospital', as: :hospital
  get 'Extended Warranties', to: 'pages#warranties', as: :warranties
  get 'Appliance Parts', to: 'pages#parts', as: :parts
  get 'Appliance Repair Near Me', to: 'pages#nearme', as: :nearme
  get 'Helpful Articles', to: 'pages#article', as: :article
  get 'Best Appliance', to: 'pages#best', as: :best
  get 'Repair Cost', to: 'pages#cost', as: :cost
  get 'pages/aux'
  root 'pages#frontdoor'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/agent.rb
class Agent < ApplicationRecord
	has_many :orders
	has_one :crew, as: :assignable

end

app/models/call.rb
class Call < ApplicationRecord
end

app/models/crew.rb
class Crew < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  before_create :generate_auth_token
  def generate_auth_token
    loop do
      self.auth_token = SecureRandom.hex
      break unless Crew.exists?(auth_token: auth_token)
    end
    self.auth_token
  end
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :assignable, polymorphic: true

end

app/models/customer.rb
class Customer < ApplicationRecord
	has_many :orders
end

app/models/day.rb
class Day < ApplicationRecord
	has_many :samsungcalls, dependent: :nullify
end

app/models/note.rb
class Note < ApplicationRecord
	validates :phone_number, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  belongs_to :agent
  belongs_to :technician

  has_many :payments
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :order
  has_many :receipts
end

app/models/receipt.rb
class Receipt < ApplicationRecord
  belongs_to :payment
end

app/models/rep.rb
class Rep < ApplicationRecord
end

app/models/samsungcall.rb
class Samsungcall < ApplicationRecord
	before_validation :set_default_phone, on: :create
	belongs_to :day, optional: true


	def set_default_phone
	    self.phone1 ||= 'none'
	    self.phone2 ||= 'none'
	end
end

app/models/technician.rb
class Technician < ApplicationRecord
	has_many :orders
	has_one :crew, as: :assignable

end

app/models/web_call.rb
class WebCall < ApplicationRecord
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :get_order
  before_action :set_payment, only: %i[ show edit update destroy ]

  # GET /payments or /payments.json
  def index
    @payments = @order.payments
  end

  # GET /payments/1 or /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = @order.payments.build
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments or /payments.json
  def create
    @payment = @order.payments.build(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to order_payment_path(@order, @payment), notice: "Payment was successfully created." }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1 or /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to order_payment_path(@order, @payment), notice: "Payment was successfully updated." }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1 or /payments/1.json
  def destroy
    @payment.destroy

    respond_to do |format|
      format.html { redirect_to order_payments_path(@order), notice: "Payment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = @order.payments.find(params[:id])
    end

    def get_order 
       @order = Order.find(params[:order_id])

    end
    # Only allow a list of trusted parameters through.
    def payment_params
      params.require(:payment).permit(:order_id, :payee, :meth, :idNum, :amount, :other)
    end
end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/helpers/calls_helper.rb
module CallsHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/reps_helper.rb
module RepsHelper
end

app/views/payments/_form.html.erb
<%= form_with(model: [@order, payment], local: true) do |form| %>
  <% if payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
        <% payment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :order_id %>
    <%= form.text_field :order_id %>
  </div>

  <div class="field">
    <%= form.label :payee %>
    <%= form.text_field :payee %>
  </div>

  <div class="field">
    <%= form.label :meth %>
    <%= form.text_field :meth %>
  </div>

  <div class="field">
    <%= form.label :idNum %>
    <%= form.text_field :idNum %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount %>
  </div>

  <div class="field">
    <%= form.label :other %>
    <%= form.text_field :other %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/payments/edit.html.erb
<h1>Editing Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Show', [@order, @payment] %> |
<%= link_to 'Back', order_payments_path(@order) %>

app/views/payments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Payments</h1>

<table>
  <thead>
    <tr>
      <th>Order</th>
      <th>Payee</th>
      <th>Method</th>
      <th>Idnum</th>
      <th>Amount</th>
      <th>Other</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.order.model %></td>
        <td><%= payment.payee %></td>
        <td><%= payment.meth %></td>
        <td><%= payment.idNum %></td>
        <td><%= payment.amount %></td>
        <td><%= payment.other %></td>
        <td><%= link_to 'Show Order', customer_order_path(@order.customer_id, @order)  %></td>
        <td><%= link_to 'Edit Order', edit_order_payment_path(@order, payment) %></td>
        <td><%= link_to 'Destroy payment', [@order, payment], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment', new_order_payment_path(@order) %>

app/views/payments/new.html.erb
<h1>New Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Back', payments_path %>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Orde:</strong>
  <%= @payment.order_id %>
</p>

<p>
  <strong>Payee:</strong>
  <%= @payment.payee %>
</p>

<p>
  <strong>Method:</strong>
  <%= @payment.meth %>
</p>

<p>
  <strong>Idnum:</strong>
  <%= @payment.idNum %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @payment.amount %>
</p>

<p>
  <strong>Other:</strong>
  <%= @payment.other %>
</p>
<h2>Recepits for this order</h2>
<% for r in @payment.receipts %>
  <ul>
    <li><%= r.recipient %></li>
    <li><%= link_to 'show Recipt', payment_receipt_path(@payment, r) %></li>
  </ul>
<% end %>

<%= link_to 'Edit', edit_order_payment_path(@order, @payment) %> |
<%= link_to 'Add recipt', payment_receipts_path(@payment) %>
<%= link_to 'Back', order_payments_path(@order) %>